# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/dms
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
           PGHOST: 127.0.0.1
           PGUSER: dms
           RAILS_ENV: test
       - image: circleci/postgres:9.6.2
         environment:
           POSTGRES_USER: dms
           POSTGRES_DB: dms_test
           POSTGRES_PASSWORD: ''
    steps:
      - checkout

      # Download and cache dependencies
      - type: cache-restore
        name: Restore bundle cache
        keys:
          - dms-bundle-{{ checksum "Gemfile.lock" }}
          - dms-bundle

      - type: cache-restore
        name: Restore yarn cache
        key: dms-bundle-{{ checksum "yarn.lock" }}

      - run:
          name: Bundle install
          command: bin/bundle check --path=vendor/bundle || bin/bundle install --path vendor/bundle

      - run:
          name: Yarn install
          command: yarn install

      - type: cache-save
        name: Store bundle cache
        key: dms-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: dms-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache

      # Database setup
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - run: mkdir /tmp/test-results
      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
