root_user_name: 'Admin'
root_user_password: 'admin123'
root_user_email: 'webadmin@ishertransport.ca'
company_name: 'ABC Company'
company_contact: 'Mark Twain'
company_phone: '604-666-1234'
company_fax: '604-666-1235'
company_email: 'info@abc.ca'
company_website: 'www.abc.ca'
company_state: 'BC'
company_currency: 'CAD'
company_last_invoice: '0'
address_line_1: '123 Street'
address_city: 'Vancouver'
address_state_province: 'BC'
address_country: 'Canada'
address_zipcode: 'V2V 1V2'
CARRIER_EMAIL_PLACEHOLDER: 'garrycheema007@gmail.com'
DMS_DATABASE_USERNAME: 'voldemort'
DMS_DATABASE_PASSWORD: ''
DEFAULT_FROM_EMAIL: 'info@isher.ca'
DMS_DATABASE_HOST: ''