default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DMS_DEV_DB_HOST") { localhost } %>
  username: <%= ENV.fetch("DMS_DEV_DB_USERNAME") { postgres } %>
  password: <%= ENV.fetch("DMS_DEV_DB_PASSWORD") { mysecretpassword } %>

development:
  <<: *default
  database: dms_development

test:
  <<: *default
  database: dms_test

production:
  <<: *default
  database: <%= ENV['DMS_PROD_DB_NAME'] %>
  host: <%= ENV['DMS_PROD_DB_HOST'] %>
  username: <%= ENV['DMS_PROD_DB_USERNAME'] %>
  password: <%= ENV['DMS_PROD_DB_PASSWORD'] %>
